"""ZAP-specific auth injection.

Nuclei and HTTPx accept `-H "<name>: <value>"` flags directly. ZAP's
`zap-baseline.py` / `zap-full-scan.py` wrappers do not — they're thin
front-ends over the ZAP daemon, and the daemon receives auth via either
context files, login users, or the Replacer addon.

The cleanest, most portable bridge is a `--hook` script: zap-baseline
loads a Python file at startup and calls `zap_started(zap, target)`,
which gives us a fully-configured `ZAPv2` client. We use it to add one
Replacer rule per header coming out of the auth profile. The rule
matches `REQ_HEADER` so it applies to every outgoing request, replacing
the value if the header already exists.

The hook file is generated per scan, stored under
`auth/zap_hooks/<uuid>.py` with 0o600 permissions, and deleted
immediately after `run_scanner()` returns (the secret never lingers).
The directory is the bind-mount source for Docker; the file's basename
becomes `<HOOK_MOUNT_DIR>/<uuid>.py` in the container thanks to the
runner's path-rewriting helper.
"""
from __future__ import annotations

import os
from pathlib import Path
from uuid import uuid4


HOOK_MOUNT_DIR = "/asura-zap-hooks"


def _hook_root() -> Path:
    """Where generated hook files live on disk.

    Inside the `auth/` directory so it inherits the same .gitignore and
    permissions story as the encrypted credential blobs themselves.
    """
    base = os.environ.get("ASURA_AUTH_DIR")
    if base:
        return Path(base) / "zap_hooks"
    return Path(__file__).resolve().parents[3] / "auth" / "zap_hooks"


def generate_hook_script(headers: list[tuple[str, str]]) -> str:
    """Return the Python source of a zap-baseline `--hook` script.

    For each (name, value) tuple the script adds one ZAP Replacer rule of
    type REQ_HEADER (matches the literal header name, replaces the value
    on every outgoing request, including new ones it adds when the header
    is absent).

    Values are embedded via `repr()` so secrets with quotes, backslashes,
    or unicode are escaped safely.
    """
    rule_lines: list[str] = []
    for idx, (name, value) in enumerate(headers):
        rule_lines.append(
            "    zap.replacer.add_rule(\n"
            f"        description={f'asura-auth-{name}'!r},\n"
            "        enabled=True,\n"
            "        matchtype='REQ_HEADER',\n"
            "        matchregex=False,\n"
            f"        matchstring={name!r},\n"
            f"        replacement={value!r},\n"
            "        initiators=None,\n"
            "    )"
        )
    body = "\n".join(rule_lines) if rule_lines else "    pass"
    return (
        "# Generated by Asura — DO NOT EDIT. Injects auth headers via the\n"
        "# ZAP Replacer addon so every outgoing request carries the\n"
        "# credentials from the selected auth profile.\n"
        "def zap_started(zap, target):\n"
        f"{body}\n"
    )


def write_hook_file(headers: list[tuple[str, str]]) -> Path:
    """Write a per-scan hook script under `auth/zap_hooks/` and return
    its absolute path. The caller owns deletion (see `delete_hook_file`).

    Permissions are tightened to 0o600 on POSIX so the file is only
    readable by the process user. No-op on Windows.
    """
    root = _hook_root()
    root.mkdir(parents=True, exist_ok=True)
    path = root / f"{uuid4().hex}.py"
    path.write_text(generate_hook_script(headers), encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return path


def delete_hook_file(path: Path) -> None:
    """Best-effort cleanup. Called from the scan loop in a try/finally so
    the hook file (which contains the decrypted secret) is removed even
    if the scanner crashes."""
    try:
        path.unlink(missing_ok=True)
    except OSError:
        pass
